/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 modelDraco.gltf
Author: Stéphane Agullo (https://sketchfab.com/sa3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lune-ecf0a02b8151418689e78abec4f94b96
Title: LUNE
*/

import React, { useRef } from 'react'
import { useGLTF} from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export function Model(props) {
  const { nodes, materials } = useGLTF('/modelDraco.gltf')
  const group=useRef();
  useFrame(() => (group.current.rotation.x += 0.001));
  
  
  return (
    

    <group ref={group} {...props} dispose={null} scale={3} >
      
      
      <mesh geometry={nodes.lune_luna_0.geometry} material={materials.luna} />
      <mesh geometry={nodes.lune_luna_0_1.geometry} material={materials.luna} />
      <mesh geometry={nodes.lune_luna_0_2.geometry} material={materials.luna} />
    </group>
  
    
  )
}

useGLTF.preload('/modelDraco.gltf')
