const SingleEventContent = [
{
    Event:"HUNARBAAZ",
    Description:"The participants will show their talents in the different divisions like dancing standup comedy, Poetry etc.",
    Duration:"2 hours Approx ",
    Venue:" Q Block Room no 001 ",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs.50",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"    
},
{
    Event:"RISKY HANDLING",
    Description:"Players must keep their hands and feet in marked position within a given time limit.",
    Duration:"1 Min per participant ",
    Venue:"In front of M block",
    Direction:"https://goo.gl/maps/P4bHTE4NjvmXTSZX7",
    Fees:"RS 50 per head ",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"RINGOZZ",
    Description:"every player will get 3 chances to put a ring on an item, the item which will come under the ring directly after being thrown will be the winner. Food items will be their biscuits packet, chocolate etc.",
    Duration:"60 Minute",
    Venue:"Management Block",
    Direction:"https://goo.gl/maps/ahUmZRXhipQddLtz9",
    Fees:"Rs.30 ",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"BLAST THE BALLOON",
    Description:"There will be two members playing; each team will get 2 minutes. One will blow the balloon and the other player will blast it by sitting on them on a chair. More balloons blasted by a player of 2 members will be the winners.",
    Duration:"25-30 MIN. (2 min for each team)",
    Venue:"In front of M block",
    Direction:"https://goo.gl/maps/P4bHTE4NjvmXTSZX7",
    Fees:"RS.50 (2 members)",
   "Approx Entries":"",
    Single:false,
    Duo:true,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"TREASURE HUNT",
    Description:"Several things will be placed at different locations students need to find them out within the given time limit.",
    Duration:"5 hrs",
    Venue:"Medi-caps University campus",
    Direction:"",
    Fees:"RS.250/- per team (5 members) ",
   "Approx Entries":"",
    Single:false,
    Duo:false,
    Team:true,
    Prices:"Exciting Prizes"   
},
{
    Event:"1 min GOLGAPPA Challenge",
    Description:"Students will be given 1 min to eat as much Pani puri as possible.",
    Duration:"2 hrs",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"RS 50 per head ",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"T-SHIRT WITH FACE PAINTING",
    Description:" Students will bring white plain t-shirts they need to colour with designs on their faces as well as t-shirts with beautiful colours.",
    Duration:"Approx 2hrs ",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"150/ team ",
   "Approx Entries":"",
    Single:false,
    Duo:true,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"BOLLYWOOD KE DRAMEBAAZ",
    Description:"Students need to come in Bollywood attire dressed in their chosen actor/actress. They have to perform a small act of at least 1 min of the chosen character.",
    Duration:"1 min",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs. 100",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:" RANGOLI MAKING",
    Description:"students will be making rangoli with beautiful colours, and they will be bringing their colours, based on beautiful and meaningful rangoli will be judged.",
    Duration:"Not Specified",
    Venue:"Q block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:" 200/team (4 per) or 50/per ",
   "Approx Entries":"",
    Single:true,
    Duo:true,
    Team:true,
    Prices:"Exciting Prizes"   
},
{
    Event:" FEEL IT REEL IT",
    Description:" Students have to make reels for 2 days on the moonstone activities the best reel will be published on the university’s social media platform with shoutouts.",
    Duration:"2 Days",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"FREE",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"BOLLYGEEKS",
    Description:"Get your bolly geek on to indulge yourself in an event full. of everything filmy! Here we'll test how in touch you are with the film-fanatic inside of you. Pucker up and tighten your belts for all things dramatic.",
    Duration:"Not Specified",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs.50/-",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"SNAKES & LADDER",
    Description:"The object of the game is to be the first player to reach the end by moving across the board from square one to the final square. Follow the numbers on the board to see how to move forward. For example, if you rolled a five and you were on space number 6, then you would move your game piece to space number 11.",
    Duration:"Not Specified",
    Venue:"Q Block ",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs.30 ",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"FUNTAKSHIRI",
    Description:"Antakshari, also known as Antyakshari is a spoken parlour game played in India. Each contestant sings the first verse of a song (often Classical Hindustani or Bollywood songs) that begins with the consonant of the Hindi alphabet on which the previous contestant's song ended.",
    Duration:"Not Specified",
    Venue:" Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs.100 per team (4 members)",
   "Approx Entries":"",
    Single:false,
    Duo:false,
    Team:true,
    Prices:"Exciting Prizes"   
},
{
    Event:"BEST FUTURE CEO",
    Description:"As a CEO, decisions making ability related to business in given situations, their attire, presentation, communication, and risk-taking ability.",
    Duration:"Not Specified",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:" Rs.250/-",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"CAMPUS BEAUTIFICATION",
    Description:"Campus Beautification competition during the event to promote environmental sustainability and awareness and give them awards.",
    Duration:"Not Specified",
    Venue:"Nearby stalls",
    Direction:"https://goo.gl/maps/Pc2Gk6YaYKRqyAuS8",
    Fees:"NIL",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"STANDUP COMEDY",
    Description:"We give all the young comedians out there a platform to tickle the audience with the best of your comic skills. Be the reason for all the giggles and laughs around, and be the best of all.",
    Duration:"Not Specified",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"RS 50 per head ",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"STOCK MAESTRO",
    Description:"Members will be allowed to trade on an intraday basis only; that is, if any team buys or sells any stock, they have to square off their position before 1:00 pm. If the team does not square off on its own, the positions will be squared off at 1:00 pm current market price, with the virtual amount given to each team to invest. Minimum 4 Scripts need to be selected by each team. At least 50% of the amount needs to be invested by every team. To buy or sell the stocks, every team needs to approach their respective student volunteers assigned at the time of the event. The prices running online on NSE will be considered for evaluation.",
    Duration:"Not Specified",
    Venue:" Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:" Team (2 members) - Rs. 200",
   "Approx Entries":"",
    Single:false,
    Duo:true,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"JO DIKHTA HE WO BIKTA HE",
    Description:"Jo Dikhta Hai Wo Bikta Hai” is a selling technique, sales presentation, or sales pitch competition. It attempts to persuade someone or something with a planned sales presentation strategy of a product, designed to initiate and close a sale of that product.",
    Duration:"",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs.200/ team",
   "Approx Entries":"",
    Single:false,
    Duo:false,
    Team:true,
    Prices:"Exciting Prizes"   
},
{
    Event:"FLIRT WITH KNIVES",
    Description:" Cooking is like painting or writing a song. Just as there are only so many notes or colours, there are only so many flavours -how you combine them sets you apart. The Master chef inside you has to showcase their marketing & selling skills as well to win this competition. Here, the chefs along with their teams will have to prepare their cuisines on campus and sell them afterwards! The team with the highest sales and the best reviews wins.",
    Duration:"Not Specified",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"Rs.100 per participant",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Exciting Prizes"   
},
{
    Event:"The SQUID GAMES",
    Description:"The Squid Game is inspired by the squid games series. In this game, there are 5-6 level games. People get eliminated at each level and there is only one final winner and the final winner will get the grand prize.",
    Duration:"Not Specified",
    Venue:"Opposite the R block",
    Direction:"https://goo.gl/maps/Pc2Gk6YaYKRqyAuS8",
    Fees:"Rs.150 per participant",
   "Approx Entries":"",
    Single:true,
    Duo:false,
    Team:false,
    Prices:"Rs.500 for the winner and Rs.200 for the Runner up"   
},
{
    Event:"BOLLYWOOD BUSINESS QUIZ",
    Description:" This quiz will be based on Bollywood theme questions.",
    Duration:"Not Specified",
    Venue:"Q Block",
    Direction:"https://goo.gl/maps/GqTYvjmS2rbeL6WD9",
    Fees:"200/ per team",
   "Approx Entries":"",
    Single:false,
    Duo:false,
    Team:true,
    Prices:"cash prize"   
}
];

export default SingleEventContent;